version: '3'
services:
  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    network_mode: bridge
    depends_on:
      - selenoid
    ports:
      - "8090:8080"
    links:
      - selenoid
    command: [ "--selenoid-uri", "http://selenoid:4444" ]