version: '3.8'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
    container_name: selenoid
    network_mode: bridge
    volumes:
      - "./config/:/etc/selenoid/" # assumed current dir contains browsers.json
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config/video:/opt/selenoid/video"
      - "./config/logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/C/Passion/dev-ops/continuous-testing/config/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-video-recorder-image", "selenoid/video-recorder:7.1", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs" ]
    ports:
      - "4444:4444"
  CONTINUOUS-TESTING-VISA-EDGE:
    image: vinothmessi/continuous-testing:v1.0
    depends_on:
      - selenoid
    network_mode: bridge
    environment:
      - PROFILE=selenoid,visa
      - BROWSER=edge
      - HOST=192.168.29.179
      - PORT=4444
      - MODULE=visa.xml
  CONTINUOUS-TESTING-RECAP-EDGE:
    image: vinothmessi/continuous-testing:v1.0
    depends_on:
      - selenoid
    network_mode: bridge
    environment:
      - PROFILE=selenoid,recap
      - BROWSER=edge
      - HOST=192.168.29.179
      - PORT=4444
      - MODULE=recap.xml

  # for starting selenoid-ui
  # docker run -d --name selenoid-ui --link selenoid -p 8090:8080 aerokube/selenoid-ui:latest-release --selenoid-uri=http://selenoid:4444