browser: chrome
timeOut: 30

report:
  name: Continuous_Testing
  path: ${user.dir}/results/reports/

snapshot:
  path: ${user.dir}/results/reports/snaps/

spring:
  profiles:
    active: local,visa
  jpa:
    defer-datasource-initialization: true