browser: firefox
timeOut: 30

project:
  name: Continuous-Testing

report:
  name: Continuous_Testing
  path: ${user.dir}/results/reports/

testdata:
  path: ${user.dir}/resources/testdata/
  name: login.yml

snapshot:
  path: ${user.dir}/results/reports/snaps/

spring:
  profiles:
    active: selenoid,visa
  jpa:
    defer-datasource-initialization: true