browser: chrome
timeOut: 30

report:
  name: Continuous_Testing
  path: ${user.dir}/results/reports/

testdata:
  path: ${user.dir}/resources/testdata/
  name: login.yml

snapshot:
  path: ${user.dir}/results/reports/snaps/

spring:
  profiles:
    active: local,recap
  jpa:
    defer-datasource-initialization: true